Repository charmbracelet/gum, pull requests merged in 2024-07, with the labels that each got.

#612 ci: sign & notarize macos binaries
  .github/workflows/goreleaser.yml
  .github/workflows/nightly.yml
Labels: enhancement

#630 ci: close milestone on release
  .goreleaser.yml
Labels: enhancement

#613 chore: remove explicitly defined max functions
  filter/filter.go
  timeout/options.go
Labels: enhancement

#483 feat(filter): Add cyclic navigation
  filter/filter.go
Labels: enhancement

#634 fix: use 0 as default width
  filter/options.go
  input/options.go
  write/options.go
Labels: bug

#639 fix: select all keybinding
  choose/command.go
  go.mod
  go.sum
Labels: bug

#640 fix: height 0 by default
  choose/options.go
  file/options.go
  table/options.go
Labels: bug, cmd/choose, cmd/file, cmd/table

#641 fix: show background style help
  style/options.go
Labels: bug
